### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by sergeevabc** [danielverh/Zippy#11]
![Uninstaller bug](https://i1.someimage.com/wXhKpuJ.png)

I’d like to get rid of Zippy, however un-installation procedure seems to be broken.

**Comment by danielverh** [comment]
Try to open the downloaded installer, and then choose remove

**Comment by sergeevabc** [comment]
There is no remove option.

**Comment by sergeevabc** [comment]
Both file system and registry are cluttered up by Zippy now.
Waiting for fixed installation package to clean all the traces.

**Comment by sergeevabc** [comment]
Thank goodness there is System Restore to rollback since author does not care about proper uninstaller.
